name: Déploiement Automatique vers le Serveur

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu pour l'exécution

    steps:
      # Étape 1 : Cloner le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer SSH pour accéder au serveur
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # Utilisation de la clé privée SSH stockée dans les secrets GitHub

      # Étape 5 : Déployer le code sur le serveur
      - name: Deploy to server
        run: |
          # Copier les fichiers backend et frontend sur le serveur via SCP
          scp -r ./backend ${{ secrets.username }}:~
          scp -r ./frontend ${{ secrets.username }}:~
          
        env:
          SSH_AUTH_SOCK: ${{ steps.ssh-agent.outputs.ssh-auth-sock }}
