name: Déploiement Automatique vers le Serveur

on:
  push:
    branches:
      - back  # Le workflow se déclenche lorsque tu fais un `push` sur la branche 'back'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu pour l'exécution

    steps:
      # Étape 1 : Cloner le code du dépôt GitHub
      - name: Checkout code
        uses: actions/checkout@v4  # Récupère le code source de la branche `back`

      # Étape 2 : Configurer SSH pour accéder au serveur
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3  # Utilise l'agent SSH pour l'authentification
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # Utilisation correcte de la clé privée SSH stockée dans les secrets GitHub

      # Étape 3 : Vérifier la connexion SSH
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ${{ secrets.username }} "echo 'SSH Connection Successful'"

      # Étape 4 : Démarrer le backend (Node.js)
      - name: Start Backend (Node.js)
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ${{ secrets.username }} << 'EOF'
            # Charger nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Si nvm est installé, le charger
            # Installer la version de Node.js et npm, si ce n'est pas déjà fait
            nvm install 16  # Utilise la version que tu as besoin
            nvm use 16      # Utilise la version de Node.js
            cd /var/www/elite/projet_sgbd/ecurie-gnak-diom-back/backend # Navigue vers le répertoire du backend
            npm install  # Installe les dépendances si nécessaire
            node ./src/server.js &  # Démarre le serveur Node.js
          EOF

      # Étape 5 : Démarrer le frontend (Next.js)
      - name: Start Frontend (Next.js)
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ${{ secrets.username }} << 'EOF'
            # Charger nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Si nvm est installé, le charger
            # Installer la version de Node.js et npm, si ce n'est pas déjà fait
            nvm install 18  # Utilise la version que tu as besoin
            nvm use 18      # Utilise la version de Node.js
            cd /var/www/elite/projet_sgbd/ecurie-gnak-diom-back/frontend  # Navigue vers le répertoire du frontend
            npm install  # Installe les dépendances si nécessaire
            npm run dev &
          EOF
